POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "date": "2025-07-02",
    "type": "Hospital",
    "specialist": "MD House",
    "diagnosisCodes": [
      "S62.5"
    ],
    "description": "yes.Another corpse.",
    "discharge": {
      "date": "never",
      "criteria": "Heart not beating."
    }
  }
